version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Docker/web/Dockerfile
    command:
      - /bin/sh
      - -c
      - |
        python manage.py collectstatic --noinput
        python manage.py makemigrations
        python manage.py migrate
        echo "WEB: Migrations process done ..."
        python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/spa_application
    env_file:
      - .env
    depends_on:
      - db
      - redis_app

  db:
    image: postgres:16.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5433:5432  # local port : container port
    expose:
      - 5432

  adminer:
    image: adminer:4.8.1
    restart: always
    depends_on:
      - db
    ports:
      - 8082:8080

  redis_app:
    image: redis:7.2.4
    ports:
      - 6379:6379
    expose:
      - 6379

volumes:
  postgres_data:
